// Code generated by tonica.dev/cli/tonica. DO NOT EDIT.
package reportsv1

import (
	"net"

	"google.golang.org/grpc"

	"github.com/tonica-go/tonica/pkg/tonica/grpc/serviceconfig"
)

const ServiceName = "reportsservice-service"
const ServiceAddrEnvName = "REPORTSSERVICE_SERVICE_GRPC_ADDR"

type ReportsServiceAddressConfig struct {
	ReportsServiceAddress  string `env:"REPORTSSERVICE_SERVICE_GRPC_ADDR,required"`
	ReportsServiceGrpcPort string `env:"REPORTSSERVICE_SERVICE_GRPC_PORT,required"`
}

func (cfg *ReportsServiceAddressConfig) CreateReportsServiceConnection() *grpc.ClientConn {
	return serviceconfig.MustCreateNewNonBlockingServiceConnection(cfg.GetReportsServiceConfig())
}

func (cfg *ReportsServiceAddressConfig) GetReportsServiceConfig() serviceconfig.ServiceConfig {
	return serviceconfig.ServiceConfig{
		Address: net.JoinHostPort(cfg.ReportsServiceAddress, cfg.ReportsServiceGrpcPort),
		Name:    ServiceName,
	}
}

func (cfg *ReportsServiceAddressConfig) CreateReportsServiceClient() ReportsServiceClient {
	return NewReportsServiceClient(cfg.CreateReportsServiceConnection())
}
