// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: reports/v1/service.proto

package reportsv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsRequest) Reset() {
	*x = ListReportsRequest{}
	mi := &file_reports_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsRequest) ProtoMessage() {}

func (x *ListReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reports_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsRequest.ProtoReflect.Descriptor instead.
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return file_reports_v1_service_proto_rawDescGZIP(), []int{0}
}

type ListReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ReportItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReportsResponse) Reset() {
	*x = ListReportsResponse{}
	mi := &file_reports_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReportsResponse) ProtoMessage() {}

func (x *ListReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reports_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReportsResponse.ProtoReflect.Descriptor instead.
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return file_reports_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListReportsResponse) GetItems() []*ReportItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_reports_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reports_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_reports_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetReportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ReportItem            `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_reports_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reports_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_reports_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetReportResponse) GetReport() *ReportItem {
	if x != nil {
		return x.Report
	}
	return nil
}

type ReportItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportItem) Reset() {
	*x = ReportItem{}
	mi := &file_reports_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportItem) ProtoMessage() {}

func (x *ReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_reports_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportItem.ProtoReflect.Descriptor instead.
func (*ReportItem) Descriptor() ([]byte, []int) {
	return file_reports_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReportItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReportItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReportItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_reports_v1_service_proto protoreflect.FileDescriptor

const file_reports_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18reports/v1/service.proto\x12\n" +
	"reports.v1\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12ListReportsRequest\"C\n" +
	"\x13ListReportsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.reports.v1.ReportItemR\x05items\"\"\n" +
	"\x10GetReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x11GetReportResponse\x12.\n" +
	"\x06report\x18\x01 \x01(\v2\x16.reports.v1.ReportItemR\x06report\"Q\n" +
	"\n" +
	"ReportItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt2\xd9\x01\n" +
	"\x0eReportsService\x12c\n" +
	"\vListReports\x12\x1e.reports.v1.ListReportsRequest\x1a\x1f.reports.v1.ListReportsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/reports\x12b\n" +
	"\tGetReport\x12\x1c.reports.v1.GetReportRequest\x1a\x1d.reports.v1.GetReportResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/reports/{id}B Z\x1eproto/gen/reports/v1;reportsv1b\x06proto3"

var (
	file_reports_v1_service_proto_rawDescOnce sync.Once
	file_reports_v1_service_proto_rawDescData []byte
)

func file_reports_v1_service_proto_rawDescGZIP() []byte {
	file_reports_v1_service_proto_rawDescOnce.Do(func() {
		file_reports_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reports_v1_service_proto_rawDesc), len(file_reports_v1_service_proto_rawDesc)))
	})
	return file_reports_v1_service_proto_rawDescData
}

var file_reports_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reports_v1_service_proto_goTypes = []any{
	(*ListReportsRequest)(nil),  // 0: reports.v1.ListReportsRequest
	(*ListReportsResponse)(nil), // 1: reports.v1.ListReportsResponse
	(*GetReportRequest)(nil),    // 2: reports.v1.GetReportRequest
	(*GetReportResponse)(nil),   // 3: reports.v1.GetReportResponse
	(*ReportItem)(nil),          // 4: reports.v1.ReportItem
}
var file_reports_v1_service_proto_depIdxs = []int32{
	4, // 0: reports.v1.ListReportsResponse.items:type_name -> reports.v1.ReportItem
	4, // 1: reports.v1.GetReportResponse.report:type_name -> reports.v1.ReportItem
	0, // 2: reports.v1.ReportsService.ListReports:input_type -> reports.v1.ListReportsRequest
	2, // 3: reports.v1.ReportsService.GetReport:input_type -> reports.v1.GetReportRequest
	1, // 4: reports.v1.ReportsService.ListReports:output_type -> reports.v1.ListReportsResponse
	3, // 5: reports.v1.ReportsService.GetReport:output_type -> reports.v1.GetReportResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_reports_v1_service_proto_init() }
func file_reports_v1_service_proto_init() {
	if File_reports_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reports_v1_service_proto_rawDesc), len(file_reports_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reports_v1_service_proto_goTypes,
		DependencyIndexes: file_reports_v1_service_proto_depIdxs,
		MessageInfos:      file_reports_v1_service_proto_msgTypes,
	}.Build()
	File_reports_v1_service_proto = out.File
	file_reports_v1_service_proto_goTypes = nil
	file_reports_v1_service_proto_depIdxs = nil
}
