// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: workflows/service.proto

package workflow

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowStatus int32

const (
	WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED      WorkflowStatus = 0
	WorkflowStatus_WORKFLOW_STATUS_RUNNING          WorkflowStatus = 1
	WorkflowStatus_WORKFLOW_STATUS_COMPLETED        WorkflowStatus = 2
	WorkflowStatus_WORKFLOW_STATUS_FAILED           WorkflowStatus = 3
	WorkflowStatus_WORKFLOW_STATUS_CANCELED         WorkflowStatus = 4
	WorkflowStatus_WORKFLOW_STATUS_TERMINATED       WorkflowStatus = 5
	WorkflowStatus_WORKFLOW_STATUS_CONTINUED_AS_NEW WorkflowStatus = 6
	WorkflowStatus_WORKFLOW_STATUS_TIMED_OUT        WorkflowStatus = 7
)

// Enum value maps for WorkflowStatus.
var (
	WorkflowStatus_name = map[int32]string{
		0: "WORKFLOW_STATUS_UNSPECIFIED",
		1: "WORKFLOW_STATUS_RUNNING",
		2: "WORKFLOW_STATUS_COMPLETED",
		3: "WORKFLOW_STATUS_FAILED",
		4: "WORKFLOW_STATUS_CANCELED",
		5: "WORKFLOW_STATUS_TERMINATED",
		6: "WORKFLOW_STATUS_CONTINUED_AS_NEW",
		7: "WORKFLOW_STATUS_TIMED_OUT",
	}
	WorkflowStatus_value = map[string]int32{
		"WORKFLOW_STATUS_UNSPECIFIED":      0,
		"WORKFLOW_STATUS_RUNNING":          1,
		"WORKFLOW_STATUS_COMPLETED":        2,
		"WORKFLOW_STATUS_FAILED":           3,
		"WORKFLOW_STATUS_CANCELED":         4,
		"WORKFLOW_STATUS_TERMINATED":       5,
		"WORKFLOW_STATUS_CONTINUED_AS_NEW": 6,
		"WORKFLOW_STATUS_TIMED_OUT":        7,
	}
)

func (x WorkflowStatus) Enum() *WorkflowStatus {
	p := new(WorkflowStatus)
	*p = x
	return p
}

func (x WorkflowStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_workflows_service_proto_enumTypes[0].Descriptor()
}

func (WorkflowStatus) Type() protoreflect.EnumType {
	return &file_workflows_service_proto_enumTypes[0]
}

func (x WorkflowStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowStatus.Descriptor instead.
func (WorkflowStatus) EnumDescriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{0}
}

type HistoryEventType int32

const (
	HistoryEventType_HISTORY_EVENT_TYPE_UNSPECIFIED                                  HistoryEventType = 0
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_STARTED                   HistoryEventType = 1
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED                 HistoryEventType = 2
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_FAILED                    HistoryEventType = 3
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT                 HistoryEventType = 4
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED                  HistoryEventType = 5
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED                HistoryEventType = 6
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_TASK_SCHEDULED                      HistoryEventType = 7
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_TASK_STARTED                        HistoryEventType = 8
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_TASK_COMPLETED                      HistoryEventType = 9
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_TASK_FAILED                         HistoryEventType = 10
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_SCHEDULED                      HistoryEventType = 11
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_STARTED                        HistoryEventType = 12
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_COMPLETED                      HistoryEventType = 13
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_FAILED                         HistoryEventType = 14
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT                      HistoryEventType = 15
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED               HistoryEventType = 16
	HistoryEventType_HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCELED                       HistoryEventType = 17
	HistoryEventType_HISTORY_EVENT_TYPE_TIMER_STARTED                                HistoryEventType = 18
	HistoryEventType_HISTORY_EVENT_TYPE_TIMER_FIRED                                  HistoryEventType = 19
	HistoryEventType_HISTORY_EVENT_TYPE_TIMER_CANCELED                               HistoryEventType = 20
	HistoryEventType_HISTORY_EVENT_TYPE_MARKER_RECORDED                              HistoryEventType = 21
	HistoryEventType_HISTORY_EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED HistoryEventType = 22
	HistoryEventType_HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED                  HistoryEventType = 23
)

// Enum value maps for HistoryEventType.
var (
	HistoryEventType_name = map[int32]string{
		0:  "HISTORY_EVENT_TYPE_UNSPECIFIED",
		1:  "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_STARTED",
		2:  "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED",
		3:  "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_FAILED",
		4:  "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT",
		5:  "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED",
		6:  "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED",
		7:  "HISTORY_EVENT_TYPE_WORKFLOW_TASK_SCHEDULED",
		8:  "HISTORY_EVENT_TYPE_WORKFLOW_TASK_STARTED",
		9:  "HISTORY_EVENT_TYPE_WORKFLOW_TASK_COMPLETED",
		10: "HISTORY_EVENT_TYPE_WORKFLOW_TASK_FAILED",
		11: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_SCHEDULED",
		12: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_STARTED",
		13: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_COMPLETED",
		14: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_FAILED",
		15: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT",
		16: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED",
		17: "HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCELED",
		18: "HISTORY_EVENT_TYPE_TIMER_STARTED",
		19: "HISTORY_EVENT_TYPE_TIMER_FIRED",
		20: "HISTORY_EVENT_TYPE_TIMER_CANCELED",
		21: "HISTORY_EVENT_TYPE_MARKER_RECORDED",
		22: "HISTORY_EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED",
		23: "HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED",
	}
	HistoryEventType_value = map[string]int32{
		"HISTORY_EVENT_TYPE_UNSPECIFIED":                                  0,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_STARTED":                   1,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED":                 2,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_FAILED":                    3,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT":                 4,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED":                  5,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED":                6,
		"HISTORY_EVENT_TYPE_WORKFLOW_TASK_SCHEDULED":                      7,
		"HISTORY_EVENT_TYPE_WORKFLOW_TASK_STARTED":                        8,
		"HISTORY_EVENT_TYPE_WORKFLOW_TASK_COMPLETED":                      9,
		"HISTORY_EVENT_TYPE_WORKFLOW_TASK_FAILED":                         10,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_SCHEDULED":                      11,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_STARTED":                        12,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_COMPLETED":                      13,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_FAILED":                         14,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT":                      15,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED":               16,
		"HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCELED":                       17,
		"HISTORY_EVENT_TYPE_TIMER_STARTED":                                18,
		"HISTORY_EVENT_TYPE_TIMER_FIRED":                                  19,
		"HISTORY_EVENT_TYPE_TIMER_CANCELED":                               20,
		"HISTORY_EVENT_TYPE_MARKER_RECORDED":                              21,
		"HISTORY_EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED": 22,
		"HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED":                  23,
	}
)

func (x HistoryEventType) Enum() *HistoryEventType {
	p := new(HistoryEventType)
	*p = x
	return p
}

func (x HistoryEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_workflows_service_proto_enumTypes[1].Descriptor()
}

func (HistoryEventType) Type() protoreflect.EnumType {
	return &file_workflows_service_proto_enumTypes[1]
}

func (x HistoryEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryEventType.Descriptor instead.
func (HistoryEventType) EnumDescriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{1}
}

type TriggerWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      string                 `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Entity        string                 `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	RecordId      string                 `protobuf:"bytes,3,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Input         map[string]string      `protobuf:"bytes,4,rep,name=input,proto3" json:"input,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Async         *bool                  `protobuf:"varint,5,opt,name=async,proto3,oneof" json:"async,omitempty"` // If true, returns immediately without waiting for completion. Default: false (waits for completion)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWorkflowRequest) Reset() {
	*x = TriggerWorkflowRequest{}
	mi := &file_workflows_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWorkflowRequest) ProtoMessage() {}

func (x *TriggerWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWorkflowRequest.ProtoReflect.Descriptor instead.
func (*TriggerWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerWorkflowRequest) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *TriggerWorkflowRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *TriggerWorkflowRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *TriggerWorkflowRequest) GetInput() map[string]string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TriggerWorkflowRequest) GetAsync() bool {
	if x != nil && x.Async != nil {
		return *x.Async
	}
	return false
}

type TriggerWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerWorkflowResponse) Reset() {
	*x = TriggerWorkflowResponse{}
	mi := &file_workflows_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerWorkflowResponse) ProtoMessage() {}

func (x *TriggerWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerWorkflowResponse.ProtoReflect.Descriptor instead.
func (*TriggerWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerWorkflowResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TriggerWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_workflows_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{2}
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_workflows_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{3}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*Namespace           `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_workflows_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListNamespacesResponse) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`  // Filter by workflow type (optional)
	Status        WorkflowStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=workflow.v1.WorkflowStatus" json:"status,omitempty"` // Filter by status (optional)
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,6,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // Free-form search query
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_workflows_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListWorkflowsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListWorkflowsRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *ListWorkflowsRequest) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *ListWorkflowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListWorkflowsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListWorkflowsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type WorkflowExecution struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId       string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId            string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowType     string                 `protobuf:"bytes,3,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Namespace        string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status           WorkflowStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=workflow.v1.WorkflowStatus" json:"status,omitempty"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	CloseTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	HistoryLength    int64                  `protobuf:"varint,8,opt,name=history_length,json=historyLength,proto3" json:"history_length,omitempty"`
	ParentWorkflowId string                 `protobuf:"bytes,9,opt,name=parent_workflow_id,json=parentWorkflowId,proto3" json:"parent_workflow_id,omitempty"`
	ParentRunId      string                 `protobuf:"bytes,10,opt,name=parent_run_id,json=parentRunId,proto3" json:"parent_run_id,omitempty"`
	SearchAttributes *structpb.Struct       `protobuf:"bytes,11,opt,name=search_attributes,json=searchAttributes,proto3" json:"search_attributes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_workflows_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowExecution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowExecution) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowExecution) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowExecution) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() WorkflowStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowStatus_WORKFLOW_STATUS_UNSPECIFIED
}

func (x *WorkflowExecution) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *WorkflowExecution) GetCloseTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CloseTime
	}
	return nil
}

func (x *WorkflowExecution) GetHistoryLength() int64 {
	if x != nil {
		return x.HistoryLength
	}
	return 0
}

func (x *WorkflowExecution) GetParentWorkflowId() string {
	if x != nil {
		return x.ParentWorkflowId
	}
	return ""
}

func (x *WorkflowExecution) GetParentRunId() string {
	if x != nil {
		return x.ParentRunId
	}
	return ""
}

func (x *WorkflowExecution) GetSearchAttributes() *structpb.Struct {
	if x != nil {
		return x.SearchAttributes
	}
	return nil
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*WorkflowExecution   `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_workflows_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkflowsResponse) GetExecutions() []*WorkflowExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListWorkflowsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Optional, uses latest if not provided
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_workflows_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type WorkflowDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Execution         *WorkflowExecution     `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	Input             *structpb.Struct       `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Result            *structpb.Struct       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	FailureMessage    *structpb.Struct       `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"` // Full failure information including cause chain
	ExecutionTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	PendingActivities []*PendingActivity     `protobuf:"bytes,6,rep,name=pending_activities,json=pendingActivities,proto3" json:"pending_activities,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowDetails) Reset() {
	*x = WorkflowDetails{}
	mi := &file_workflows_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDetails) ProtoMessage() {}

func (x *WorkflowDetails) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDetails.ProtoReflect.Descriptor instead.
func (*WorkflowDetails) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowDetails) GetExecution() *WorkflowExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *WorkflowDetails) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WorkflowDetails) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowDetails) GetFailureMessage() *structpb.Struct {
	if x != nil {
		return x.FailureMessage
	}
	return nil
}

func (x *WorkflowDetails) GetExecutionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutionTime
	}
	return nil
}

func (x *WorkflowDetails) GetPendingActivities() []*PendingActivity {
	if x != nil {
		return x.PendingActivities
	}
	return nil
}

type PendingActivity struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActivityId        string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityType      string                 `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	ScheduledTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	Attempt           int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastHeartbeatTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PendingActivity) Reset() {
	*x = PendingActivity{}
	mi := &file_workflows_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingActivity) ProtoMessage() {}

func (x *PendingActivity) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingActivity.ProtoReflect.Descriptor instead.
func (*PendingActivity) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{10}
}

func (x *PendingActivity) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *PendingActivity) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *PendingActivity) GetScheduledTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledTime
	}
	return nil
}

func (x *PendingActivity) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *PendingActivity) GetLastHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatTime
	}
	return nil
}

type GetWorkflowHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Optional
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowHistoryRequest) Reset() {
	*x = GetWorkflowHistoryRequest{}
	mi := &file_workflows_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowHistoryRequest) ProtoMessage() {}

func (x *GetWorkflowHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowHistoryRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetWorkflowHistoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetWorkflowHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowHistoryRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetWorkflowHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetWorkflowHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type HistoryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	EventType     HistoryEventType       `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=workflow.v1.HistoryEventType" json:"event_type,omitempty"`
	TaskId        int64                  `protobuf:"varint,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,5,opt,name=attributes,proto3" json:"attributes,omitempty"`                // Event-specific attributes
	EventName     string                 `protobuf:"bytes,6,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"` // Human-readable event name (activity name, timer ID, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEvent) Reset() {
	*x = HistoryEvent{}
	mi := &file_workflows_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEvent) ProtoMessage() {}

func (x *HistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEvent.ProtoReflect.Descriptor instead.
func (*HistoryEvent) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *HistoryEvent) GetEventTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTime
	}
	return nil
}

func (x *HistoryEvent) GetEventType() HistoryEventType {
	if x != nil {
		return x.EventType
	}
	return HistoryEventType_HISTORY_EVENT_TYPE_UNSPECIFIED
}

func (x *HistoryEvent) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *HistoryEvent) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *HistoryEvent) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

type GetWorkflowHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*HistoryEvent        `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowHistoryResponse) Reset() {
	*x = GetWorkflowHistoryResponse{}
	mi := &file_workflows_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowHistoryResponse) ProtoMessage() {}

func (x *GetWorkflowHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowHistoryResponse) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetWorkflowHistoryResponse) GetHistory() []*HistoryEvent {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetWorkflowHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type TerminateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Optional
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateWorkflowRequest) Reset() {
	*x = TerminateWorkflowRequest{}
	mi := &file_workflows_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateWorkflowRequest) ProtoMessage() {}

func (x *TerminateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*TerminateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{14}
}

func (x *TerminateWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TerminateWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TerminateWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TerminateWorkflowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_workflows_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{15}
}

func (x *CancelWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CancelWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type SignalWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Optional
	SignalName    string                 `protobuf:"bytes,4,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowRequest) Reset() {
	*x = SignalWorkflowRequest{}
	mi := &file_workflows_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowRequest) ProtoMessage() {}

func (x *SignalWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SignalWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{16}
}

func (x *SignalWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SignalWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflowRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type RestartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Run ID to restart from
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartWorkflowRequest) Reset() {
	*x = RestartWorkflowRequest{}
	mi := &file_workflows_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartWorkflowRequest) ProtoMessage() {}

func (x *RestartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RestartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{17}
}

func (x *RestartWorkflowRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RestartWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RestartWorkflowRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RestartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartWorkflowResponse) Reset() {
	*x = RestartWorkflowResponse{}
	mi := &file_workflows_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartWorkflowResponse) ProtoMessage() {}

func (x *RestartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*RestartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{18}
}

func (x *RestartWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RestartWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_workflows_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListSchedulesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListSchedulesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSchedulesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type Schedule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId     string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	WorkflowType   string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	CronExpression string                 `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"`
	NextRunTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_run_time,json=nextRunTime,proto3" json:"next_run_time,omitempty"`
	LastRunTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_run_time,json=lastRunTime,proto3" json:"last_run_time,omitempty"`
	Paused         bool                   `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"`
	Notes          string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	WorkflowInput  *structpb.Struct       `protobuf:"bytes,8,opt,name=workflow_input,json=workflowInput,proto3" json:"workflow_input,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Schedule) Reset() {
	*x = Schedule{}
	mi := &file_workflows_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schedule) ProtoMessage() {}

func (x *Schedule) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schedule.ProtoReflect.Descriptor instead.
func (*Schedule) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{20}
}

func (x *Schedule) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *Schedule) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *Schedule) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *Schedule) GetNextRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunTime
	}
	return nil
}

func (x *Schedule) GetLastRunTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunTime
	}
	return nil
}

func (x *Schedule) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *Schedule) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Schedule) GetWorkflowInput() *structpb.Struct {
	if x != nil {
		return x.WorkflowInput
	}
	return nil
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*Schedule            `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_workflows_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{21}
}

func (x *ListSchedulesResponse) GetSchedules() []*Schedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *ListSchedulesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleRequest) Reset() {
	*x = GetScheduleRequest{}
	mi := &file_workflows_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleRequest) ProtoMessage() {}

func (x *GetScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetScheduleRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type PauseScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleRequest) Reset() {
	*x = PauseScheduleRequest{}
	mi := &file_workflows_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleRequest) ProtoMessage() {}

func (x *PauseScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleRequest.ProtoReflect.Descriptor instead.
func (*PauseScheduleRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{23}
}

func (x *PauseScheduleRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PauseScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *PauseScheduleRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type UnpauseScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpauseScheduleRequest) Reset() {
	*x = UnpauseScheduleRequest{}
	mi := &file_workflows_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpauseScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpauseScheduleRequest) ProtoMessage() {}

func (x *UnpauseScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpauseScheduleRequest.ProtoReflect.Descriptor instead.
func (*UnpauseScheduleRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{24}
}

func (x *UnpauseScheduleRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UnpauseScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *UnpauseScheduleRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type TriggerScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScheduleRequest) Reset() {
	*x = TriggerScheduleRequest{}
	mi := &file_workflows_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduleRequest) ProtoMessage() {}

func (x *TriggerScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflows_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduleRequest.ProtoReflect.Descriptor instead.
func (*TriggerScheduleRequest) Descriptor() ([]byte, []int) {
	return file_workflows_service_proto_rawDescGZIP(), []int{25}
}

func (x *TriggerScheduleRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TriggerScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

var File_workflows_service_proto protoreflect.FileDescriptor

const file_workflows_service_proto_rawDesc = "" +
	"\n" +
	"\x17workflows/service.proto\x12\vworkflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8e\x02\n" +
	"\x16TriggerWorkflowRequest\x12\x1a\n" +
	"\bworkflow\x18\x01 \x01(\tR\bworkflow\x12\x16\n" +
	"\x06entity\x18\x02 \x01(\tR\x06entity\x12\x1b\n" +
	"\trecord_id\x18\x03 \x01(\tR\brecordId\x12D\n" +
	"\x05input\x18\x04 \x03(\v2..workflow.v1.TriggerWorkflowRequest.InputEntryR\x05input\x12\x19\n" +
	"\x05async\x18\x05 \x01(\bH\x00R\x05async\x88\x01\x01\x1a8\n" +
	"\n" +
	"InputEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_async\"T\n" +
	"\x17TriggerWorkflowResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x17\n" +
	"\x15ListNamespacesRequest\"A\n" +
	"\tNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"P\n" +
	"\x16ListNamespacesResponse\x126\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x16.workflow.v1.NamespaceR\n" +
	"namespaces\"\xed\x01\n" +
	"\x14ListWorkflowsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.workflow.v1.WorkflowStatusR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12!\n" +
	"\fsearch_query\x18\x06 \x01(\tR\vsearchQuery\"\xf8\x03\n" +
	"\x11WorkflowExecution\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_type\x18\x03 \x01(\tR\fworkflowType\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.workflow.v1.WorkflowStatusR\x06status\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x129\n" +
	"\n" +
	"close_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcloseTime\x12%\n" +
	"\x0ehistory_length\x18\b \x01(\x03R\rhistoryLength\x12,\n" +
	"\x12parent_workflow_id\x18\t \x01(\tR\x10parentWorkflowId\x12\"\n" +
	"\rparent_run_id\x18\n" +
	" \x01(\tR\vparentRunId\x12D\n" +
	"\x11search_attributes\x18\v \x01(\v2\x17.google.protobuf.StructR\x10searchAttributes\"\x7f\n" +
	"\x15ListWorkflowsResponse\x12>\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2\x1e.workflow.v1.WorkflowExecutionR\n" +
	"executions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"j\n" +
	"\x12GetWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\x81\x03\n" +
	"\x0fWorkflowDetails\x12<\n" +
	"\texecution\x18\x01 \x01(\v2\x1e.workflow.v1.WorkflowExecutionR\texecution\x12-\n" +
	"\x05input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05input\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\x12@\n" +
	"\x0ffailure_message\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x0efailureMessage\x12A\n" +
	"\x0eexecution_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rexecutionTime\x12K\n" +
	"\x12pending_activities\x18\x06 \x03(\v2\x1c.workflow.v1.PendingActivityR\x11pendingActivities\"\x80\x02\n" +
	"\x0fPendingActivity\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12#\n" +
	"\ractivity_type\x18\x02 \x01(\tR\factivityType\x12A\n" +
	"\x0escheduled_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rscheduledTime\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12J\n" +
	"\x13last_heartbeat_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11lastHeartbeatTime\"\xad\x01\n" +
	"\x19GetWorkflowHistoryRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x93\x02\n" +
	"\fHistoryEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x129\n" +
	"\n" +
	"event_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\teventTime\x12<\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2\x1d.workflow.v1.HistoryEventTypeR\teventType\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\x03R\x06taskId\x127\n" +
	"\n" +
	"attributes\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"event_name\x18\x06 \x01(\tR\teventName\"y\n" +
	"\x1aGetWorkflowHistoryResponse\x123\n" +
	"\ahistory\x18\x01 \x03(\v2\x19.workflow.v1.HistoryEventR\ahistory\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x88\x01\n" +
	"\x18TerminateWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"m\n" +
	"\x15CancelWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\xbd\x01\n" +
	"\x15SignalWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1f\n" +
	"\vsignal_name\x18\x04 \x01(\tR\n" +
	"signalName\x12-\n" +
	"\x05input\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05input\"n\n" +
	"\x16RestartWorkflowRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"Q\n" +
	"\x17RestartWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"p\n" +
	"\x14ListSchedulesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xe7\x02\n" +
	"\bSchedule\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12'\n" +
	"\x0fcron_expression\x18\x03 \x01(\tR\x0ecronExpression\x12>\n" +
	"\rnext_run_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vnextRunTime\x12>\n" +
	"\rlast_run_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastRunTime\x12\x16\n" +
	"\x06paused\x18\x06 \x01(\bR\x06paused\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12>\n" +
	"\x0eworkflow_input\x18\b \x01(\v2\x17.google.protobuf.StructR\rworkflowInput\"t\n" +
	"\x15ListSchedulesResponse\x123\n" +
	"\tschedules\x18\x01 \x03(\v2\x15.workflow.v1.ScheduleR\tschedules\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x12GetScheduleRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\"i\n" +
	"\x14PauseScheduleRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"k\n" +
	"\x16UnpauseScheduleRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12\x12\n" +
	"\x04note\x18\x03 \x01(\tR\x04note\"W\n" +
	"\x16TriggerScheduleRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId*\x8c\x02\n" +
	"\x0eWorkflowStatus\x12\x1f\n" +
	"\x1bWORKFLOW_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKFLOW_STATUS_RUNNING\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16WORKFLOW_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18WORKFLOW_STATUS_CANCELED\x10\x04\x12\x1e\n" +
	"\x1aWORKFLOW_STATUS_TERMINATED\x10\x05\x12$\n" +
	" WORKFLOW_STATUS_CONTINUED_AS_NEW\x10\x06\x12\x1d\n" +
	"\x19WORKFLOW_STATUS_TIMED_OUT\x10\a*\x8d\t\n" +
	"\x10HistoryEventType\x12\"\n" +
	"\x1eHISTORY_EVENT_TYPE_UNSPECIFIED\x10\x00\x121\n" +
	"-HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_STARTED\x10\x01\x123\n" +
	"/HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED\x10\x02\x120\n" +
	",HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_FAILED\x10\x03\x123\n" +
	"/HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT\x10\x04\x122\n" +
	".HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED\x10\x05\x124\n" +
	"0HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED\x10\x06\x12.\n" +
	"*HISTORY_EVENT_TYPE_WORKFLOW_TASK_SCHEDULED\x10\a\x12,\n" +
	"(HISTORY_EVENT_TYPE_WORKFLOW_TASK_STARTED\x10\b\x12.\n" +
	"*HISTORY_EVENT_TYPE_WORKFLOW_TASK_COMPLETED\x10\t\x12+\n" +
	"'HISTORY_EVENT_TYPE_WORKFLOW_TASK_FAILED\x10\n" +
	"\x12.\n" +
	"*HISTORY_EVENT_TYPE_ACTIVITY_TASK_SCHEDULED\x10\v\x12,\n" +
	"(HISTORY_EVENT_TYPE_ACTIVITY_TASK_STARTED\x10\f\x12.\n" +
	"*HISTORY_EVENT_TYPE_ACTIVITY_TASK_COMPLETED\x10\r\x12+\n" +
	"'HISTORY_EVENT_TYPE_ACTIVITY_TASK_FAILED\x10\x0e\x12.\n" +
	"*HISTORY_EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT\x10\x0f\x125\n" +
	"1HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED\x10\x10\x12-\n" +
	")HISTORY_EVENT_TYPE_ACTIVITY_TASK_CANCELED\x10\x11\x12$\n" +
	" HISTORY_EVENT_TYPE_TIMER_STARTED\x10\x12\x12\"\n" +
	"\x1eHISTORY_EVENT_TYPE_TIMER_FIRED\x10\x13\x12%\n" +
	"!HISTORY_EVENT_TYPE_TIMER_CANCELED\x10\x14\x12&\n" +
	"\"HISTORY_EVENT_TYPE_MARKER_RECORDED\x10\x15\x12C\n" +
	"?HISTORY_EVENT_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_INITIATED\x10\x16\x122\n" +
	".HISTORY_EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED\x10\x172\xf9\x0f\n" +
	"\x0fWorkflowService\x12\x82\x01\n" +
	"\x0fTriggerWorkflow\x12#.workflow.v1.TriggerWorkflowRequest\x1a$.workflow.v1.TriggerWorkflowResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/workflows/trigger\x12\x7f\n" +
	"\x0eListNamespaces\x12\".workflow.v1.ListNamespacesRequest\x1a#.workflow.v1.ListNamespacesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/workflows/namespaces\x12{\n" +
	"\rListWorkflows\x12!.workflow.v1.ListWorkflowsRequest\x1a\".workflow.v1.ListWorkflowsResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/workflows/search\x12\x81\x01\n" +
	"\vGetWorkflow\x12\x1f.workflow.v1.GetWorkflowRequest\x1a\x1c.workflow.v1.WorkflowDetails\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/workflows/{namespace}/{workflow_id}\x12\xa2\x01\n" +
	"\x12GetWorkflowHistory\x12&.workflow.v1.GetWorkflowHistoryRequest\x1a'.workflow.v1.GetWorkflowHistoryResponse\";\x82\xd3\xe4\x93\x025\x123/api/v1/workflows/{namespace}/{workflow_id}/history\x12\x94\x01\n" +
	"\x11TerminateWorkflow\x12%.workflow.v1.TerminateWorkflowRequest\x1a\x16.google.protobuf.Empty\"@\x82\xd3\xe4\x93\x02::\x01*\"5/api/v1/workflows/{namespace}/{workflow_id}/terminate\x12\x8b\x01\n" +
	"\x0eCancelWorkflow\x12\".workflow.v1.CancelWorkflowRequest\x1a\x16.google.protobuf.Empty\"=\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/workflows/{namespace}/{workflow_id}/cancel\x12\x8b\x01\n" +
	"\x0eSignalWorkflow\x12\".workflow.v1.SignalWorkflowRequest\x1a\x16.google.protobuf.Empty\"=\x82\xd3\xe4\x93\x027:\x01*\"2/api/v1/workflows/{namespace}/{workflow_id}/signal\x12\x9c\x01\n" +
	"\x0fRestartWorkflow\x12#.workflow.v1.RestartWorkflowRequest\x1a$.workflow.v1.RestartWorkflowResponse\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/v1/workflows/{namespace}/{workflow_id}/restart\x12\x87\x01\n" +
	"\rListSchedules\x12!.workflow.v1.ListSchedulesRequest\x1a\".workflow.v1.ListSchedulesResponse\"/\x82\xd3\xe4\x93\x02)\x12'/api/v1/workflows/{namespace}/schedules\x12\x84\x01\n" +
	"\vGetSchedule\x12\x1f.workflow.v1.GetScheduleRequest\x1a\x15.workflow.v1.Schedule\"=\x82\xd3\xe4\x93\x027\x125/api/v1/workflows/{namespace}/schedules/{schedule_id}\x12\x92\x01\n" +
	"\rPauseSchedule\x12!.workflow.v1.PauseScheduleRequest\x1a\x16.google.protobuf.Empty\"F\x82\xd3\xe4\x93\x02@:\x01*\";/api/v1/workflows/{namespace}/schedules/{schedule_id}/pause\x12\x98\x01\n" +
	"\x0fUnpauseSchedule\x12#.workflow.v1.UnpauseScheduleRequest\x1a\x16.google.protobuf.Empty\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/api/v1/workflows/{namespace}/schedules/{schedule_id}/unpause\x12\xa6\x01\n" +
	"\x0fTriggerSchedule\x12#.workflow.v1.TriggerScheduleRequest\x1a$.workflow.v1.TriggerWorkflowResponse\"H\x82\xd3\xe4\x93\x02B:\x01*\"=/api/v1/workflows/{namespace}/schedules/{schedule_id}/triggerB\x1dZ\x1bproto/gen/workflow;workflowb\x06proto3"

var (
	file_workflows_service_proto_rawDescOnce sync.Once
	file_workflows_service_proto_rawDescData []byte
)

func file_workflows_service_proto_rawDescGZIP() []byte {
	file_workflows_service_proto_rawDescOnce.Do(func() {
		file_workflows_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflows_service_proto_rawDesc), len(file_workflows_service_proto_rawDesc)))
	})
	return file_workflows_service_proto_rawDescData
}

var file_workflows_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_workflows_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_workflows_service_proto_goTypes = []any{
	(WorkflowStatus)(0),                // 0: workflow.v1.WorkflowStatus
	(HistoryEventType)(0),              // 1: workflow.v1.HistoryEventType
	(*TriggerWorkflowRequest)(nil),     // 2: workflow.v1.TriggerWorkflowRequest
	(*TriggerWorkflowResponse)(nil),    // 3: workflow.v1.TriggerWorkflowResponse
	(*ListNamespacesRequest)(nil),      // 4: workflow.v1.ListNamespacesRequest
	(*Namespace)(nil),                  // 5: workflow.v1.Namespace
	(*ListNamespacesResponse)(nil),     // 6: workflow.v1.ListNamespacesResponse
	(*ListWorkflowsRequest)(nil),       // 7: workflow.v1.ListWorkflowsRequest
	(*WorkflowExecution)(nil),          // 8: workflow.v1.WorkflowExecution
	(*ListWorkflowsResponse)(nil),      // 9: workflow.v1.ListWorkflowsResponse
	(*GetWorkflowRequest)(nil),         // 10: workflow.v1.GetWorkflowRequest
	(*WorkflowDetails)(nil),            // 11: workflow.v1.WorkflowDetails
	(*PendingActivity)(nil),            // 12: workflow.v1.PendingActivity
	(*GetWorkflowHistoryRequest)(nil),  // 13: workflow.v1.GetWorkflowHistoryRequest
	(*HistoryEvent)(nil),               // 14: workflow.v1.HistoryEvent
	(*GetWorkflowHistoryResponse)(nil), // 15: workflow.v1.GetWorkflowHistoryResponse
	(*TerminateWorkflowRequest)(nil),   // 16: workflow.v1.TerminateWorkflowRequest
	(*CancelWorkflowRequest)(nil),      // 17: workflow.v1.CancelWorkflowRequest
	(*SignalWorkflowRequest)(nil),      // 18: workflow.v1.SignalWorkflowRequest
	(*RestartWorkflowRequest)(nil),     // 19: workflow.v1.RestartWorkflowRequest
	(*RestartWorkflowResponse)(nil),    // 20: workflow.v1.RestartWorkflowResponse
	(*ListSchedulesRequest)(nil),       // 21: workflow.v1.ListSchedulesRequest
	(*Schedule)(nil),                   // 22: workflow.v1.Schedule
	(*ListSchedulesResponse)(nil),      // 23: workflow.v1.ListSchedulesResponse
	(*GetScheduleRequest)(nil),         // 24: workflow.v1.GetScheduleRequest
	(*PauseScheduleRequest)(nil),       // 25: workflow.v1.PauseScheduleRequest
	(*UnpauseScheduleRequest)(nil),     // 26: workflow.v1.UnpauseScheduleRequest
	(*TriggerScheduleRequest)(nil),     // 27: workflow.v1.TriggerScheduleRequest
	nil,                                // 28: workflow.v1.TriggerWorkflowRequest.InputEntry
	(*timestamppb.Timestamp)(nil),      // 29: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 30: google.protobuf.Struct
	(*emptypb.Empty)(nil),              // 31: google.protobuf.Empty
}
var file_workflows_service_proto_depIdxs = []int32{
	28, // 0: workflow.v1.TriggerWorkflowRequest.input:type_name -> workflow.v1.TriggerWorkflowRequest.InputEntry
	5,  // 1: workflow.v1.ListNamespacesResponse.namespaces:type_name -> workflow.v1.Namespace
	0,  // 2: workflow.v1.ListWorkflowsRequest.status:type_name -> workflow.v1.WorkflowStatus
	0,  // 3: workflow.v1.WorkflowExecution.status:type_name -> workflow.v1.WorkflowStatus
	29, // 4: workflow.v1.WorkflowExecution.start_time:type_name -> google.protobuf.Timestamp
	29, // 5: workflow.v1.WorkflowExecution.close_time:type_name -> google.protobuf.Timestamp
	30, // 6: workflow.v1.WorkflowExecution.search_attributes:type_name -> google.protobuf.Struct
	8,  // 7: workflow.v1.ListWorkflowsResponse.executions:type_name -> workflow.v1.WorkflowExecution
	8,  // 8: workflow.v1.WorkflowDetails.execution:type_name -> workflow.v1.WorkflowExecution
	30, // 9: workflow.v1.WorkflowDetails.input:type_name -> google.protobuf.Struct
	30, // 10: workflow.v1.WorkflowDetails.result:type_name -> google.protobuf.Struct
	30, // 11: workflow.v1.WorkflowDetails.failure_message:type_name -> google.protobuf.Struct
	29, // 12: workflow.v1.WorkflowDetails.execution_time:type_name -> google.protobuf.Timestamp
	12, // 13: workflow.v1.WorkflowDetails.pending_activities:type_name -> workflow.v1.PendingActivity
	29, // 14: workflow.v1.PendingActivity.scheduled_time:type_name -> google.protobuf.Timestamp
	29, // 15: workflow.v1.PendingActivity.last_heartbeat_time:type_name -> google.protobuf.Timestamp
	29, // 16: workflow.v1.HistoryEvent.event_time:type_name -> google.protobuf.Timestamp
	1,  // 17: workflow.v1.HistoryEvent.event_type:type_name -> workflow.v1.HistoryEventType
	30, // 18: workflow.v1.HistoryEvent.attributes:type_name -> google.protobuf.Struct
	14, // 19: workflow.v1.GetWorkflowHistoryResponse.history:type_name -> workflow.v1.HistoryEvent
	30, // 20: workflow.v1.SignalWorkflowRequest.input:type_name -> google.protobuf.Struct
	29, // 21: workflow.v1.Schedule.next_run_time:type_name -> google.protobuf.Timestamp
	29, // 22: workflow.v1.Schedule.last_run_time:type_name -> google.protobuf.Timestamp
	30, // 23: workflow.v1.Schedule.workflow_input:type_name -> google.protobuf.Struct
	22, // 24: workflow.v1.ListSchedulesResponse.schedules:type_name -> workflow.v1.Schedule
	2,  // 25: workflow.v1.WorkflowService.TriggerWorkflow:input_type -> workflow.v1.TriggerWorkflowRequest
	4,  // 26: workflow.v1.WorkflowService.ListNamespaces:input_type -> workflow.v1.ListNamespacesRequest
	7,  // 27: workflow.v1.WorkflowService.ListWorkflows:input_type -> workflow.v1.ListWorkflowsRequest
	10, // 28: workflow.v1.WorkflowService.GetWorkflow:input_type -> workflow.v1.GetWorkflowRequest
	13, // 29: workflow.v1.WorkflowService.GetWorkflowHistory:input_type -> workflow.v1.GetWorkflowHistoryRequest
	16, // 30: workflow.v1.WorkflowService.TerminateWorkflow:input_type -> workflow.v1.TerminateWorkflowRequest
	17, // 31: workflow.v1.WorkflowService.CancelWorkflow:input_type -> workflow.v1.CancelWorkflowRequest
	18, // 32: workflow.v1.WorkflowService.SignalWorkflow:input_type -> workflow.v1.SignalWorkflowRequest
	19, // 33: workflow.v1.WorkflowService.RestartWorkflow:input_type -> workflow.v1.RestartWorkflowRequest
	21, // 34: workflow.v1.WorkflowService.ListSchedules:input_type -> workflow.v1.ListSchedulesRequest
	24, // 35: workflow.v1.WorkflowService.GetSchedule:input_type -> workflow.v1.GetScheduleRequest
	25, // 36: workflow.v1.WorkflowService.PauseSchedule:input_type -> workflow.v1.PauseScheduleRequest
	26, // 37: workflow.v1.WorkflowService.UnpauseSchedule:input_type -> workflow.v1.UnpauseScheduleRequest
	27, // 38: workflow.v1.WorkflowService.TriggerSchedule:input_type -> workflow.v1.TriggerScheduleRequest
	3,  // 39: workflow.v1.WorkflowService.TriggerWorkflow:output_type -> workflow.v1.TriggerWorkflowResponse
	6,  // 40: workflow.v1.WorkflowService.ListNamespaces:output_type -> workflow.v1.ListNamespacesResponse
	9,  // 41: workflow.v1.WorkflowService.ListWorkflows:output_type -> workflow.v1.ListWorkflowsResponse
	11, // 42: workflow.v1.WorkflowService.GetWorkflow:output_type -> workflow.v1.WorkflowDetails
	15, // 43: workflow.v1.WorkflowService.GetWorkflowHistory:output_type -> workflow.v1.GetWorkflowHistoryResponse
	31, // 44: workflow.v1.WorkflowService.TerminateWorkflow:output_type -> google.protobuf.Empty
	31, // 45: workflow.v1.WorkflowService.CancelWorkflow:output_type -> google.protobuf.Empty
	31, // 46: workflow.v1.WorkflowService.SignalWorkflow:output_type -> google.protobuf.Empty
	20, // 47: workflow.v1.WorkflowService.RestartWorkflow:output_type -> workflow.v1.RestartWorkflowResponse
	23, // 48: workflow.v1.WorkflowService.ListSchedules:output_type -> workflow.v1.ListSchedulesResponse
	22, // 49: workflow.v1.WorkflowService.GetSchedule:output_type -> workflow.v1.Schedule
	31, // 50: workflow.v1.WorkflowService.PauseSchedule:output_type -> google.protobuf.Empty
	31, // 51: workflow.v1.WorkflowService.UnpauseSchedule:output_type -> google.protobuf.Empty
	3,  // 52: workflow.v1.WorkflowService.TriggerSchedule:output_type -> workflow.v1.TriggerWorkflowResponse
	39, // [39:53] is the sub-list for method output_type
	25, // [25:39] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_workflows_service_proto_init() }
func file_workflows_service_proto_init() {
	if File_workflows_service_proto != nil {
		return
	}
	file_workflows_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflows_service_proto_rawDesc), len(file_workflows_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflows_service_proto_goTypes,
		DependencyIndexes: file_workflows_service_proto_depIdxs,
		EnumInfos:         file_workflows_service_proto_enumTypes,
		MessageInfos:      file_workflows_service_proto_msgTypes,
	}.Build()
	File_workflows_service_proto = out.File
	file_workflows_service_proto_goTypes = nil
	file_workflows_service_proto_depIdxs = nil
}
