// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: entities/entities.proto

package entities

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_FIELD_TYPE_UNSPECIFIED FieldType = 0
	FieldType_FIELD_TYPE_STRING      FieldType = 1
	FieldType_FIELD_TYPE_NUMBER      FieldType = 2
	FieldType_FIELD_TYPE_BOOLEAN     FieldType = 3
	FieldType_FIELD_TYPE_DATETIME    FieldType = 4
	FieldType_FIELD_TYPE_UUID        FieldType = 5
	FieldType_FIELD_TYPE_ENUM        FieldType = 6
	FieldType_FIELD_TYPE_OBJECT      FieldType = 7
	FieldType_FIELD_TYPE_ARRAY       FieldType = 8
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "FIELD_TYPE_UNSPECIFIED",
		1: "FIELD_TYPE_STRING",
		2: "FIELD_TYPE_NUMBER",
		3: "FIELD_TYPE_BOOLEAN",
		4: "FIELD_TYPE_DATETIME",
		5: "FIELD_TYPE_UUID",
		6: "FIELD_TYPE_ENUM",
		7: "FIELD_TYPE_OBJECT",
		8: "FIELD_TYPE_ARRAY",
	}
	FieldType_value = map[string]int32{
		"FIELD_TYPE_UNSPECIFIED": 0,
		"FIELD_TYPE_STRING":      1,
		"FIELD_TYPE_NUMBER":      2,
		"FIELD_TYPE_BOOLEAN":     3,
		"FIELD_TYPE_DATETIME":    4,
		"FIELD_TYPE_UUID":        5,
		"FIELD_TYPE_ENUM":        6,
		"FIELD_TYPE_OBJECT":      7,
		"FIELD_TYPE_ARRAY":       8,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_entities_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_entities_entities_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{0}
}

type FilterOperator int32

const (
	FilterOperator_FILTER_OPERATOR_UNSPECIFIED FilterOperator = 0
	FilterOperator_FILTER_OPERATOR_EQ          FilterOperator = 1
	FilterOperator_FILTER_OPERATOR_NE          FilterOperator = 2
	FilterOperator_FILTER_OPERATOR_CONTAINS    FilterOperator = 3
	FilterOperator_FILTER_OPERATOR_IN          FilterOperator = 4
	FilterOperator_FILTER_OPERATOR_GT          FilterOperator = 5
	FilterOperator_FILTER_OPERATOR_GTE         FilterOperator = 6
	FilterOperator_FILTER_OPERATOR_LT          FilterOperator = 7
	FilterOperator_FILTER_OPERATOR_LTE         FilterOperator = 8
)

// Enum value maps for FilterOperator.
var (
	FilterOperator_name = map[int32]string{
		0: "FILTER_OPERATOR_UNSPECIFIED",
		1: "FILTER_OPERATOR_EQ",
		2: "FILTER_OPERATOR_NE",
		3: "FILTER_OPERATOR_CONTAINS",
		4: "FILTER_OPERATOR_IN",
		5: "FILTER_OPERATOR_GT",
		6: "FILTER_OPERATOR_GTE",
		7: "FILTER_OPERATOR_LT",
		8: "FILTER_OPERATOR_LTE",
	}
	FilterOperator_value = map[string]int32{
		"FILTER_OPERATOR_UNSPECIFIED": 0,
		"FILTER_OPERATOR_EQ":          1,
		"FILTER_OPERATOR_NE":          2,
		"FILTER_OPERATOR_CONTAINS":    3,
		"FILTER_OPERATOR_IN":          4,
		"FILTER_OPERATOR_GT":          5,
		"FILTER_OPERATOR_GTE":         6,
		"FILTER_OPERATOR_LT":          7,
		"FILTER_OPERATOR_LTE":         8,
	}
)

func (x FilterOperator) Enum() *FilterOperator {
	p := new(FilterOperator)
	*p = x
	return p
}

func (x FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_entities_proto_enumTypes[1].Descriptor()
}

func (FilterOperator) Type() protoreflect.EnumType {
	return &file_entities_entities_proto_enumTypes[1]
}

func (x FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperator.Descriptor instead.
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{1}
}

type SortDirection int32

const (
	SortDirection_SORT_DIRECTION_UNSPECIFIED SortDirection = 0
	SortDirection_SORT_DIRECTION_ASC         SortDirection = 1
	SortDirection_SORT_DIRECTION_DESC        SortDirection = 2
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_UNSPECIFIED",
		1: "SORT_DIRECTION_ASC",
		2: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_UNSPECIFIED": 0,
		"SORT_DIRECTION_ASC":         1,
		"SORT_DIRECTION_DESC":        2,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_entities_proto_enumTypes[2].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_entities_entities_proto_enumTypes[2]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{2}
}

type FilterDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operators     []FilterOperator       `protobuf:"varint,1,rep,packed,name=operators,proto3,enum=entities.v1.FilterOperator" json:"operators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterDefinition) Reset() {
	*x = FilterDefinition{}
	mi := &file_entities_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterDefinition) ProtoMessage() {}

func (x *FilterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterDefinition.ProtoReflect.Descriptor instead.
func (*FilterDefinition) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{0}
}

func (x *FilterDefinition) GetOperators() []FilterOperator {
	if x != nil {
		return x.Operators
	}
	return nil
}

type FieldDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Type          FieldType              `protobuf:"varint,3,opt,name=type,proto3,enum=entities.v1.FieldType" json:"type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Sortable      bool                   `protobuf:"varint,6,opt,name=sortable,proto3" json:"sortable,omitempty"`
	Filter        *FilterDefinition      `protobuf:"bytes,7,opt,name=filter,proto3" json:"filter,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDefinition) Reset() {
	*x = FieldDefinition{}
	mi := &file_entities_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinition) ProtoMessage() {}

func (x *FieldDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinition.ProtoReflect.Descriptor instead.
func (*FieldDefinition) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{1}
}

func (x *FieldDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FieldDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *FieldDefinition) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_FIELD_TYPE_UNSPECIFIED
}

func (x *FieldDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldDefinition) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

func (x *FieldDefinition) GetSortable() bool {
	if x != nil {
		return x.Sortable
	}
	return false
}

func (x *FieldDefinition) GetFilter() *FilterDefinition {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *FieldDefinition) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EntityDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PrimaryKey    string                 `protobuf:"bytes,4,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	Fields        []*FieldDefinition     `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityDefinition) Reset() {
	*x = EntityDefinition{}
	mi := &file_entities_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityDefinition) ProtoMessage() {}

func (x *EntityDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityDefinition.ProtoReflect.Descriptor instead.
func (*EntityDefinition) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{2}
}

func (x *EntityDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *EntityDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EntityDefinition) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *EntityDefinition) GetFields() []*FieldDefinition {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *EntityDefinition) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*EntityDefinition    `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_entities_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{3}
}

func (x *ListEntitiesResponse) GetEntities() []*EntityDefinition {
	if x != nil {
		return x.Entities
	}
	return nil
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_entities_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{4}
}

func (x *GetEntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecordMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,5,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordMetadata) Reset() {
	*x = RecordMetadata{}
	mi := &file_entities_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordMetadata) ProtoMessage() {}

func (x *RecordMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordMetadata.ProtoReflect.Descriptor instead.
func (*RecordMetadata) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{5}
}

func (x *RecordMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecordMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RecordMetadata) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *RecordMetadata) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *RecordMetadata        `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_entities_entities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Record) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Record) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Record) GetMetadata() *RecordMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FilterExpression struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      FilterOperator         `protobuf:"varint,2,opt,name=operator,proto3,enum=entities.v1.FilterOperator" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterExpression) Reset() {
	*x = FilterExpression{}
	mi := &file_entities_entities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterExpression) ProtoMessage() {}

func (x *FilterExpression) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterExpression.ProtoReflect.Descriptor instead.
func (*FilterExpression) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{7}
}

func (x *FilterExpression) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FilterExpression) GetOperator() FilterOperator {
	if x != nil {
		return x.Operator
	}
	return FilterOperator_FILTER_OPERATOR_UNSPECIFIED
}

func (x *FilterExpression) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListRecordsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Filters       []*FilterExpression    `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	SortField     string                 `protobuf:"bytes,5,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	SortDirection SortDirection          `protobuf:"varint,6,opt,name=sort_direction,json=sortDirection,proto3,enum=entities.v1.SortDirection" json:"sort_direction,omitempty"`
	Search        string                 `protobuf:"bytes,7,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsRequest) Reset() {
	*x = ListRecordsRequest{}
	mi := &file_entities_entities_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsRequest) ProtoMessage() {}

func (x *ListRecordsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsRequest.ProtoReflect.Descriptor instead.
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{8}
}

func (x *ListRecordsRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *ListRecordsRequest) GetFilters() []*FilterExpression {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *ListRecordsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRecordsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRecordsRequest) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *ListRecordsRequest) GetSortDirection() SortDirection {
	if x != nil {
		return x.SortDirection
	}
	return SortDirection_SORT_DIRECTION_UNSPECIFIED
}

func (x *ListRecordsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListRecordsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordsResponse) Reset() {
	*x = ListRecordsResponse{}
	mi := &file_entities_entities_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordsResponse) ProtoMessage() {}

func (x *ListRecordsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordsResponse.ProtoReflect.Descriptor instead.
func (*ListRecordsResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{9}
}

func (x *ListRecordsResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ListRecordsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_entities_entities_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecordRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *GetRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_entities_entities_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRecordRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *CreateRecordRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecordRequest) Reset() {
	*x = UpdateRecordRequest{}
	mi := &file_entities_entities_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecordRequest) ProtoMessage() {}

func (x *UpdateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecordRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecordRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRecordRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *UpdateRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRecordRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecordRequest) Reset() {
	*x = DeleteRecordRequest{}
	mi := &file_entities_entities_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecordRequest) ProtoMessage() {}

func (x *DeleteRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecordRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecordRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRecordRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *DeleteRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRecordHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordHistoryRequest) Reset() {
	*x = ListRecordHistoryRequest{}
	mi := &file_entities_entities_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordHistoryRequest) ProtoMessage() {}

func (x *ListRecordHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListRecordHistoryRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{14}
}

func (x *ListRecordHistoryRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *ListRecordHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListRecordHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRecordHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type RecordHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	RawPayload    string                 `protobuf:"bytes,6,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	Deleted       bool                   `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordHistoryEntry) Reset() {
	*x = RecordHistoryEntry{}
	mi := &file_entities_entities_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordHistoryEntry) ProtoMessage() {}

func (x *RecordHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordHistoryEntry.ProtoReflect.Descriptor instead.
func (*RecordHistoryEntry) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{15}
}

func (x *RecordHistoryEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RecordHistoryEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordHistoryEntry) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *RecordHistoryEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *RecordHistoryEntry) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecordHistoryEntry) GetRawPayload() string {
	if x != nil {
		return x.RawPayload
	}
	return ""
}

func (x *RecordHistoryEntry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ListRecordHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*RecordHistoryEntry  `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecordHistoryResponse) Reset() {
	*x = ListRecordHistoryResponse{}
	mi := &file_entities_entities_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecordHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecordHistoryResponse) ProtoMessage() {}

func (x *ListRecordHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecordHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListRecordHistoryResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{16}
}

func (x *ListRecordHistoryResponse) GetHistory() []*RecordHistoryEntry {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ListRecordHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type PivotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        string                 `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	RowField      string                 `protobuf:"bytes,2,opt,name=row_field,json=rowField,proto3" json:"row_field,omitempty"`
	ColumnField   string                 `protobuf:"bytes,3,opt,name=column_field,json=columnField,proto3" json:"column_field,omitempty"`
	Filters       []*FilterExpression    `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PivotRequest) Reset() {
	*x = PivotRequest{}
	mi := &file_entities_entities_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PivotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PivotRequest) ProtoMessage() {}

func (x *PivotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PivotRequest.ProtoReflect.Descriptor instead.
func (*PivotRequest) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{17}
}

func (x *PivotRequest) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *PivotRequest) GetRowField() string {
	if x != nil {
		return x.RowField
	}
	return ""
}

func (x *PivotRequest) GetColumnField() string {
	if x != nil {
		return x.ColumnField
	}
	return ""
}

func (x *PivotRequest) GetFilters() []*FilterExpression {
	if x != nil {
		return x.Filters
	}
	return nil
}

type PivotEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowKey        string                 `protobuf:"bytes,1,opt,name=row_key,json=rowKey,proto3" json:"row_key,omitempty"`
	ColumnKey     string                 `protobuf:"bytes,2,opt,name=column_key,json=columnKey,proto3" json:"column_key,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PivotEntry) Reset() {
	*x = PivotEntry{}
	mi := &file_entities_entities_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PivotEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PivotEntry) ProtoMessage() {}

func (x *PivotEntry) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PivotEntry.ProtoReflect.Descriptor instead.
func (*PivotEntry) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{18}
}

func (x *PivotEntry) GetRowKey() string {
	if x != nil {
		return x.RowKey
	}
	return ""
}

func (x *PivotEntry) GetColumnKey() string {
	if x != nil {
		return x.ColumnKey
	}
	return ""
}

func (x *PivotEntry) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PivotTotals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           map[string]float64     `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Column        map[string]float64     `protobuf:"bytes,2,rep,name=column,proto3" json:"column,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Grand         float64                `protobuf:"fixed64,3,opt,name=grand,proto3" json:"grand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PivotTotals) Reset() {
	*x = PivotTotals{}
	mi := &file_entities_entities_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PivotTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PivotTotals) ProtoMessage() {}

func (x *PivotTotals) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PivotTotals.ProtoReflect.Descriptor instead.
func (*PivotTotals) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{19}
}

func (x *PivotTotals) GetRow() map[string]float64 {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *PivotTotals) GetColumn() map[string]float64 {
	if x != nil {
		return x.Column
	}
	return nil
}

func (x *PivotTotals) GetGrand() float64 {
	if x != nil {
		return x.Grand
	}
	return 0
}

type PivotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowField      string                 `protobuf:"bytes,1,opt,name=row_field,json=rowField,proto3" json:"row_field,omitempty"`
	ColumnField   string                 `protobuf:"bytes,2,opt,name=column_field,json=columnField,proto3" json:"column_field,omitempty"`
	Entries       []*PivotEntry          `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Totals        *PivotTotals           `protobuf:"bytes,4,opt,name=totals,proto3" json:"totals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PivotResponse) Reset() {
	*x = PivotResponse{}
	mi := &file_entities_entities_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PivotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PivotResponse) ProtoMessage() {}

func (x *PivotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entities_entities_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PivotResponse.ProtoReflect.Descriptor instead.
func (*PivotResponse) Descriptor() ([]byte, []int) {
	return file_entities_entities_proto_rawDescGZIP(), []int{20}
}

func (x *PivotResponse) GetRowField() string {
	if x != nil {
		return x.RowField
	}
	return ""
}

func (x *PivotResponse) GetColumnField() string {
	if x != nil {
		return x.ColumnField
	}
	return ""
}

func (x *PivotResponse) GetEntries() []*PivotEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *PivotResponse) GetTotals() *PivotTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

var File_entities_entities_proto protoreflect.FileDescriptor

const file_entities_entities_proto_rawDesc = "" +
	"\n" +
	"\x17entities/entities.proto\x12\ventities.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"M\n" +
	"\x10FilterDefinition\x129\n" +
	"\toperators\x18\x01 \x03(\x0e2\x1b.entities.v1.FilterOperatorR\toperators\"\x80\x03\n" +
	"\x0fFieldDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.entities.v1.FieldTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\x12\x1a\n" +
	"\bsortable\x18\x06 \x01(\bR\bsortable\x125\n" +
	"\x06filter\x18\a \x01(\v2\x1d.entities.v1.FilterDefinitionR\x06filter\x12F\n" +
	"\bmetadata\x18\b \x03(\v2*.entities.v1.FieldDefinition.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x02\n" +
	"\x10EntityDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprimary_key\x18\x04 \x01(\tR\n" +
	"primaryKey\x124\n" +
	"\x06fields\x18\x05 \x03(\v2\x1c.entities.v1.FieldDefinitionR\x06fields\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.entities.v1.EntityDefinition.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x14ListEntitiesResponse\x129\n" +
	"\bentities\x18\x01 \x03(\v2\x1d.entities.v1.EntityDefinitionR\bentities\"\"\n" +
	"\x10GetEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd4\x01\n" +
	"\x0eRecordMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x05 \x01(\tR\tupdatedBy\"\x96\x01\n" +
	"\x06Record\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x127\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1b.entities.v1.RecordMetadataR\bmetadata\"\x8f\x01\n" +
	"\x10FilterExpression\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x127\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1b.entities.v1.FilterOperatorR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\"\x9b\x02\n" +
	"\x12ListRecordsRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x127\n" +
	"\afilters\x18\x02 \x03(\v2\x1d.entities.v1.FilterExpressionR\afilters\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x05 \x01(\tR\tsortField\x12A\n" +
	"\x0esort_direction\x18\x06 \x01(\x0e2\x1a.entities.v1.SortDirectionR\rsortDirection\x12\x16\n" +
	"\x06search\x18\a \x01(\tR\x06search\"l\n" +
	"\x13ListRecordsResponse\x12-\n" +
	"\arecords\x18\x01 \x03(\v2\x13.entities.v1.RecordR\arecords\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\":\n" +
	"\x10GetRecordRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Z\n" +
	"\x13CreateRecordRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"j\n" +
	"\x13UpdateRecordRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\"=\n" +
	"\x13DeleteRecordRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"~\n" +
	"\x18ListRecordHistoryRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x88\x02\n" +
	"\x12RecordHistoryEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12+\n" +
	"\x04data\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x1f\n" +
	"\vraw_payload\x18\x06 \x01(\tR\n" +
	"rawPayload\x12\x18\n" +
	"\adeleted\x18\a \x01(\bR\adeleted\"~\n" +
	"\x19ListRecordHistoryResponse\x129\n" +
	"\ahistory\x18\x01 \x03(\v2\x1f.entities.v1.RecordHistoryEntryR\ahistory\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9f\x01\n" +
	"\fPivotRequest\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x1b\n" +
	"\trow_field\x18\x02 \x01(\tR\browField\x12!\n" +
	"\fcolumn_field\x18\x03 \x01(\tR\vcolumnField\x127\n" +
	"\afilters\x18\x04 \x03(\v2\x1d.entities.v1.FilterExpressionR\afilters\"Z\n" +
	"\n" +
	"PivotEntry\x12\x17\n" +
	"\arow_key\x18\x01 \x01(\tR\x06rowKey\x12\x1d\n" +
	"\n" +
	"column_key\x18\x02 \x01(\tR\tcolumnKey\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\"\x89\x02\n" +
	"\vPivotTotals\x123\n" +
	"\x03row\x18\x01 \x03(\v2!.entities.v1.PivotTotals.RowEntryR\x03row\x12<\n" +
	"\x06column\x18\x02 \x03(\v2$.entities.v1.PivotTotals.ColumnEntryR\x06column\x12\x14\n" +
	"\x05grand\x18\x03 \x01(\x01R\x05grand\x1a6\n" +
	"\bRowEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a9\n" +
	"\vColumnEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb4\x01\n" +
	"\rPivotResponse\x12\x1b\n" +
	"\trow_field\x18\x01 \x01(\tR\browField\x12!\n" +
	"\fcolumn_field\x18\x02 \x01(\tR\vcolumnField\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.entities.v1.PivotEntryR\aentries\x120\n" +
	"\x06totals\x18\x04 \x01(\v2\x18.entities.v1.PivotTotalsR\x06totals*\xdd\x01\n" +
	"\tFieldType\x12\x1a\n" +
	"\x16FIELD_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11FIELD_TYPE_STRING\x10\x01\x12\x15\n" +
	"\x11FIELD_TYPE_NUMBER\x10\x02\x12\x16\n" +
	"\x12FIELD_TYPE_BOOLEAN\x10\x03\x12\x17\n" +
	"\x13FIELD_TYPE_DATETIME\x10\x04\x12\x13\n" +
	"\x0fFIELD_TYPE_UUID\x10\x05\x12\x13\n" +
	"\x0fFIELD_TYPE_ENUM\x10\x06\x12\x15\n" +
	"\x11FIELD_TYPE_OBJECT\x10\a\x12\x14\n" +
	"\x10FIELD_TYPE_ARRAY\x10\b*\xf9\x01\n" +
	"\x0eFilterOperator\x12\x1f\n" +
	"\x1bFILTER_OPERATOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FILTER_OPERATOR_EQ\x10\x01\x12\x16\n" +
	"\x12FILTER_OPERATOR_NE\x10\x02\x12\x1c\n" +
	"\x18FILTER_OPERATOR_CONTAINS\x10\x03\x12\x16\n" +
	"\x12FILTER_OPERATOR_IN\x10\x04\x12\x16\n" +
	"\x12FILTER_OPERATOR_GT\x10\x05\x12\x17\n" +
	"\x13FILTER_OPERATOR_GTE\x10\x06\x12\x16\n" +
	"\x12FILTER_OPERATOR_LT\x10\a\x12\x17\n" +
	"\x13FILTER_OPERATOR_LTE\x10\b*`\n" +
	"\rSortDirection\x12\x1e\n" +
	"\x1aSORT_DIRECTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SORT_DIRECTION_ASC\x10\x01\x12\x17\n" +
	"\x13SORT_DIRECTION_DESC\x10\x022\xbd\b\n" +
	"\rEntityService\x12c\n" +
	"\fListEntities\x12\x16.google.protobuf.Empty\x1a!.entities.v1.ListEntitiesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/entities\x12h\n" +
	"\tGetEntity\x12\x1d.entities.v1.GetEntityRequest\x1a\x1d.entities.v1.EntityDefinition\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/entities/{id}\x12\x9a\x01\n" +
	"\vListRecords\x12\x1f.entities.v1.ListRecordsRequest\x1a .entities.v1.ListRecordsResponse\"H\x82\xd3\xe4\x93\x02B:\x01*Z\x1b\x12\x19/api/v1/entities/{entity}\" /api/v1/entities/{entity}/search\x12g\n" +
	"\tGetRecord\x12\x1d.entities.v1.GetRecordRequest\x1a\x13.entities.v1.Record\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/entities/{entity}/{id}\x12k\n" +
	"\fCreateRecord\x12 .entities.v1.CreateRecordRequest\x1a\x13.entities.v1.Record\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/entities/{entity}\x12p\n" +
	"\fUpdateRecord\x12 .entities.v1.UpdateRecordRequest\x1a\x13.entities.v1.Record\")\x82\xd3\xe4\x93\x02#:\x01*\x1a\x1e/api/v1/entities/{entity}/{id}\x12p\n" +
	"\fDeleteRecord\x12 .entities.v1.DeleteRecordRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 *\x1e/api/v1/entities/{entity}/{id}\x12\x92\x01\n" +
	"\x11ListRecordHistory\x12%.entities.v1.ListRecordHistoryRequest\x1a&.entities.v1.ListRecordHistoryResponse\".\x82\xd3\xe4\x93\x02(\x12&/api/v1/entities/{entity}/{id}/history\x12q\n" +
	"\fPivotRecords\x12\x19.entities.v1.PivotRequest\x1a\x1a.entities.v1.PivotResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/entities/{entity}/pivotB\x1dZ\x1bproto/gen/entities;entitiesb\x06proto3"

var (
	file_entities_entities_proto_rawDescOnce sync.Once
	file_entities_entities_proto_rawDescData []byte
)

func file_entities_entities_proto_rawDescGZIP() []byte {
	file_entities_entities_proto_rawDescOnce.Do(func() {
		file_entities_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_entities_proto_rawDesc), len(file_entities_entities_proto_rawDesc)))
	})
	return file_entities_entities_proto_rawDescData
}

var file_entities_entities_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_entities_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_entities_entities_proto_goTypes = []any{
	(FieldType)(0),                    // 0: entities.v1.FieldType
	(FilterOperator)(0),               // 1: entities.v1.FilterOperator
	(SortDirection)(0),                // 2: entities.v1.SortDirection
	(*FilterDefinition)(nil),          // 3: entities.v1.FilterDefinition
	(*FieldDefinition)(nil),           // 4: entities.v1.FieldDefinition
	(*EntityDefinition)(nil),          // 5: entities.v1.EntityDefinition
	(*ListEntitiesResponse)(nil),      // 6: entities.v1.ListEntitiesResponse
	(*GetEntityRequest)(nil),          // 7: entities.v1.GetEntityRequest
	(*RecordMetadata)(nil),            // 8: entities.v1.RecordMetadata
	(*Record)(nil),                    // 9: entities.v1.Record
	(*FilterExpression)(nil),          // 10: entities.v1.FilterExpression
	(*ListRecordsRequest)(nil),        // 11: entities.v1.ListRecordsRequest
	(*ListRecordsResponse)(nil),       // 12: entities.v1.ListRecordsResponse
	(*GetRecordRequest)(nil),          // 13: entities.v1.GetRecordRequest
	(*CreateRecordRequest)(nil),       // 14: entities.v1.CreateRecordRequest
	(*UpdateRecordRequest)(nil),       // 15: entities.v1.UpdateRecordRequest
	(*DeleteRecordRequest)(nil),       // 16: entities.v1.DeleteRecordRequest
	(*ListRecordHistoryRequest)(nil),  // 17: entities.v1.ListRecordHistoryRequest
	(*RecordHistoryEntry)(nil),        // 18: entities.v1.RecordHistoryEntry
	(*ListRecordHistoryResponse)(nil), // 19: entities.v1.ListRecordHistoryResponse
	(*PivotRequest)(nil),              // 20: entities.v1.PivotRequest
	(*PivotEntry)(nil),                // 21: entities.v1.PivotEntry
	(*PivotTotals)(nil),               // 22: entities.v1.PivotTotals
	(*PivotResponse)(nil),             // 23: entities.v1.PivotResponse
	nil,                               // 24: entities.v1.FieldDefinition.MetadataEntry
	nil,                               // 25: entities.v1.EntityDefinition.MetadataEntry
	nil,                               // 26: entities.v1.PivotTotals.RowEntry
	nil,                               // 27: entities.v1.PivotTotals.ColumnEntry
	(*timestamppb.Timestamp)(nil),     // 28: google.protobuf.Timestamp
	(*structpb.Struct)(nil),           // 29: google.protobuf.Struct
	(*structpb.Value)(nil),            // 30: google.protobuf.Value
	(*emptypb.Empty)(nil),             // 31: google.protobuf.Empty
}
var file_entities_entities_proto_depIdxs = []int32{
	1,  // 0: entities.v1.FilterDefinition.operators:type_name -> entities.v1.FilterOperator
	0,  // 1: entities.v1.FieldDefinition.type:type_name -> entities.v1.FieldType
	3,  // 2: entities.v1.FieldDefinition.filter:type_name -> entities.v1.FilterDefinition
	24, // 3: entities.v1.FieldDefinition.metadata:type_name -> entities.v1.FieldDefinition.MetadataEntry
	4,  // 4: entities.v1.EntityDefinition.fields:type_name -> entities.v1.FieldDefinition
	25, // 5: entities.v1.EntityDefinition.metadata:type_name -> entities.v1.EntityDefinition.MetadataEntry
	5,  // 6: entities.v1.ListEntitiesResponse.entities:type_name -> entities.v1.EntityDefinition
	28, // 7: entities.v1.RecordMetadata.created_at:type_name -> google.protobuf.Timestamp
	28, // 8: entities.v1.RecordMetadata.updated_at:type_name -> google.protobuf.Timestamp
	29, // 9: entities.v1.Record.data:type_name -> google.protobuf.Struct
	8,  // 10: entities.v1.Record.metadata:type_name -> entities.v1.RecordMetadata
	1,  // 11: entities.v1.FilterExpression.operator:type_name -> entities.v1.FilterOperator
	30, // 12: entities.v1.FilterExpression.value:type_name -> google.protobuf.Value
	10, // 13: entities.v1.ListRecordsRequest.filters:type_name -> entities.v1.FilterExpression
	2,  // 14: entities.v1.ListRecordsRequest.sort_direction:type_name -> entities.v1.SortDirection
	9,  // 15: entities.v1.ListRecordsResponse.records:type_name -> entities.v1.Record
	29, // 16: entities.v1.CreateRecordRequest.data:type_name -> google.protobuf.Struct
	29, // 17: entities.v1.UpdateRecordRequest.data:type_name -> google.protobuf.Struct
	28, // 18: entities.v1.RecordHistoryEntry.occurred_at:type_name -> google.protobuf.Timestamp
	29, // 19: entities.v1.RecordHistoryEntry.data:type_name -> google.protobuf.Struct
	18, // 20: entities.v1.ListRecordHistoryResponse.history:type_name -> entities.v1.RecordHistoryEntry
	10, // 21: entities.v1.PivotRequest.filters:type_name -> entities.v1.FilterExpression
	26, // 22: entities.v1.PivotTotals.row:type_name -> entities.v1.PivotTotals.RowEntry
	27, // 23: entities.v1.PivotTotals.column:type_name -> entities.v1.PivotTotals.ColumnEntry
	21, // 24: entities.v1.PivotResponse.entries:type_name -> entities.v1.PivotEntry
	22, // 25: entities.v1.PivotResponse.totals:type_name -> entities.v1.PivotTotals
	31, // 26: entities.v1.EntityService.ListEntities:input_type -> google.protobuf.Empty
	7,  // 27: entities.v1.EntityService.GetEntity:input_type -> entities.v1.GetEntityRequest
	11, // 28: entities.v1.EntityService.ListRecords:input_type -> entities.v1.ListRecordsRequest
	13, // 29: entities.v1.EntityService.GetRecord:input_type -> entities.v1.GetRecordRequest
	14, // 30: entities.v1.EntityService.CreateRecord:input_type -> entities.v1.CreateRecordRequest
	15, // 31: entities.v1.EntityService.UpdateRecord:input_type -> entities.v1.UpdateRecordRequest
	16, // 32: entities.v1.EntityService.DeleteRecord:input_type -> entities.v1.DeleteRecordRequest
	17, // 33: entities.v1.EntityService.ListRecordHistory:input_type -> entities.v1.ListRecordHistoryRequest
	20, // 34: entities.v1.EntityService.PivotRecords:input_type -> entities.v1.PivotRequest
	6,  // 35: entities.v1.EntityService.ListEntities:output_type -> entities.v1.ListEntitiesResponse
	5,  // 36: entities.v1.EntityService.GetEntity:output_type -> entities.v1.EntityDefinition
	12, // 37: entities.v1.EntityService.ListRecords:output_type -> entities.v1.ListRecordsResponse
	9,  // 38: entities.v1.EntityService.GetRecord:output_type -> entities.v1.Record
	9,  // 39: entities.v1.EntityService.CreateRecord:output_type -> entities.v1.Record
	9,  // 40: entities.v1.EntityService.UpdateRecord:output_type -> entities.v1.Record
	31, // 41: entities.v1.EntityService.DeleteRecord:output_type -> google.protobuf.Empty
	19, // 42: entities.v1.EntityService.ListRecordHistory:output_type -> entities.v1.ListRecordHistoryResponse
	23, // 43: entities.v1.EntityService.PivotRecords:output_type -> entities.v1.PivotResponse
	35, // [35:44] is the sub-list for method output_type
	26, // [26:35] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_entities_entities_proto_init() }
func file_entities_entities_proto_init() {
	if File_entities_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_entities_proto_rawDesc), len(file_entities_entities_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entities_entities_proto_goTypes,
		DependencyIndexes: file_entities_entities_proto_depIdxs,
		EnumInfos:         file_entities_entities_proto_enumTypes,
		MessageInfos:      file_entities_entities_proto_msgTypes,
	}.Build()
	File_entities_entities_proto = out.File
	file_entities_entities_proto_goTypes = nil
	file_entities_entities_proto_depIdxs = nil
}
